// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi4N9yLSfj6tcfJQf_Mg9dXa3A7UWmbNI',
    appId: '1:538369039643:web:cef14c4b63a011dfcd87be',
    messagingSenderId: '538369039643',
    projectId: 'mini-e-commerce-app-n4',
    authDomain: 'mini-e-commerce-app-n4.firebaseapp.com',
    storageBucket: 'mini-e-commerce-app-n4.firebasestorage.app',
    measurementId: 'G-8ZMJ14XC7P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaR88dimosspOlxk4LZl1CZZOE-jEkK-U',
    appId: '1:538369039643:android:f243d6155a36d3a1cd87be',
    messagingSenderId: '538369039643',
    projectId: 'mini-e-commerce-app-n4',
    storageBucket: 'mini-e-commerce-app-n4.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATpVOIeGLqqlb9n3xHlTpLRQk6hcXEsLI',
    appId: '1:538369039643:ios:39a2e3b33de94431cd87be',
    messagingSenderId: '538369039643',
    projectId: 'mini-e-commerce-app-n4',
    storageBucket: 'mini-e-commerce-app-n4.firebasestorage.app',
    iosBundleId: 'com.example.miniEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi4N9yLSfj6tcfJQf_Mg9dXa3A7UWmbNI',
    appId: '1:538369039643:web:bb89d9f1b447358bcd87be',
    messagingSenderId: '538369039643',
    projectId: 'mini-e-commerce-app-n4',
    authDomain: 'mini-e-commerce-app-n4.firebaseapp.com',
    storageBucket: 'mini-e-commerce-app-n4.firebasestorage.app',
    measurementId: 'G-QVJ4SKQTR6',
  );
}
